// lib/mock-data.ts
export const mockSpeakers = [
  {
    id: '1',
    name: 'Dr. Aminata A Haidara',
    title: 'Directrice Régionale',
    organization: 'UNICEF Mali',
    bio: 'Spécialiste en développement de l\'enfance avec 20 ans d\'expérience en Afrique de l\'Ouest.',
    bio_en: 'Child development specialist with 20 years of experience in West Africa.',
    avatar: '/intervenants/Ada.jpeg',
    domain: 'Protection de l\'enfance',
    domain_en: 'Child Protection',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-1', 'panel-3'],
    featured: true,
  },
  {
    id: '2',
    name: 'Ibrahim Konaté',
    title: 'Secrétaire Général',
    organization: 'Croix-Rouge Malienne',
    bio: 'Expert en réponse humanitaire d\'urgence et en gestion des catastrophes naturelles.',
    bio_en: 'Expert in emergency humanitarian response and natural disaster management.',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    domain: 'Aide humanitaire',
    domain_en: 'Humanitarian Aid',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-1', 'panel-2'],
    featured: true,
  },
  {
    id: '3',
    name: 'Fatoumata Coulibaly',
    title: 'Coordinatrice Nationale',
    organization: 'ONU Femmes Mali',
    bio: 'Militante pour l\'égalité des genres et l\'autonomisation économique des femmes rurales.',
    bio_en: 'Advocate for gender equality and economic empowerment of rural women.',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    domain: 'Genre & Développement',
    domain_en: 'Gender & Development',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-2'],
    featured: true,
  },
  {
    id: '4',
    name: 'Dr. Moussa Traoré',
    title: 'Directeur Médical',
    organization: 'Médecins Sans Frontières',
    bio: 'Chirurgien humanitaire ayant travaillé dans 15 pays en situation de crise.',
    bio_en: 'Humanitarian surgeon having worked in 15 countries in crisis situations.',
    avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
    domain: 'Santé',
    domain_en: 'Health',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-3'],
    featured: false,
  },
  {
    id: '5',
    name: 'Aïssata Sanogo',
    title: 'Responsable Programmes',
    organization: 'Plan International Mali',
    bio: 'Experte en éducation inclusive et protection des droits des filles dans les zones de conflit.',
    bio_en: 'Expert in inclusive education and protection of girls\' rights in conflict zones.',
    avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
    domain: 'Éducation',
    domain_en: 'Education',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-2', 'panel-3'],
    featured: false,
  },
  {
    id: '6',
    name: 'Oumar Diarra',
    title: 'Consultant Senior',
    organization: 'Banque Mondiale',
    bio: 'Économiste spécialisé dans le financement du développement et la gouvernance locale.',
    bio_en: 'Economist specializing in development finance and local governance.',
    avatar: 'https://randomuser.me/api/portraits/men/78.jpg',
    domain: 'Économie & Finance',
    domain_en: 'Economy & Finance',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-1'],
    featured: false,
  },
  {
    id: '7',
    name: 'Mariam Sissoko',
    title: 'Présidente',
    organization: 'RECOTRADE',
    bio: 'Pionnière de l\'entrepreneuriat social féminin au Mali et en Afrique subsaharienne.',
    bio_en: 'Pioneer of female social entrepreneurship in Mali and sub-Saharan Africa.',
    avatar: 'https://randomuser.me/api/portraits/women/55.jpg',
    domain: 'Entrepreneuriat Social',
    domain_en: 'Social Entrepreneurship',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-2'],
    featured: false,
  },
  {
    id: '8',
    name: 'Sékou Bah',
    title: 'Directeur Pays',
    organization: 'Catholic Relief Services',
    bio: 'Expert en sécurité alimentaire et en résilience des communautés agricoles vulnérables.',
    bio_en: 'Expert in food security and resilience of vulnerable farming communities.',
    avatar: 'https://randomuser.me/api/portraits/men/91.jpg',
    domain: 'Sécurité Alimentaire',
    domain_en: 'Food Security',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-1', 'panel-3'],
    featured: false,
  },
  {
    id: '9',
    name: 'Kadiatou Barry',
    title: 'Chargée de Mission',
    organization: 'USAID Mali',
    bio: 'Spécialiste en gouvernance décentralisée et renforcement des capacités institutionnelles.',
    bio_en: 'Specialist in decentralized governance and institutional capacity building.',
    avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    domain: 'Gouvernance',
    domain_en: 'Governance',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-3'],
    featured: false,
  },
  {
    id: '10',
    name: 'Boubacar Keïta',
    title: 'Fondateur & CEO',
    organization: 'TechSolve Africa',
    bio: 'Entrepreneur tech développant des solutions numériques innovantes pour les ONG africaines.',
    bio_en: 'Tech entrepreneur developing innovative digital solutions for African NGOs.',
    avatar: 'https://randomuser.me/api/portraits/men/44.jpg',
    domain: 'Innovation & Tech',
    domain_en: 'Innovation & Tech',
    linkedin: 'https://linkedin.com',
    sessions: ['panel-2'],
    featured: false,
  },
]

export const mockPanels = [
  {
    id: 'panel-1',
    day: 1,
    date: '2026-05-14',
    startTime: '09:00',
    endTime: '11:00',
    title: 'Financement de l\'action humanitaire au Mali : Enjeux et perspectives',
    title_en: 'Financing humanitarian action in Mali: Challenges and perspectives',
    description: 'Ce panel réunira bailleurs de fonds, ONG et gouvernement pour discuter des mécanismes innovants de financement du développement durable au Mali.',
    description_en: 'This panel brings together donors, NGOs and government to discuss innovative mechanisms for sustainable development financing in Mali.',
    room: 'Grande Salle – Palais des Congrès',
    capacity: 200,
    registered: 147,
    speakers: ['1', '2', '6', '8'],
    category: 'Plénière',
    category_en: 'Plenary',
    color: '#1e3a8a',
  },
  {
    id: 'panel-2',
    day: 1,
    date: '2026-05-14',
    startTime: '14:00',
    endTime: '16:00',
    title: 'Genre, autonomisation et développement inclusif',
    title_en: 'Gender, empowerment and inclusive development',
    description: 'Atelier interactif sur les stratégies d\'intégration du genre dans les programmes humanitaires et de développement au Mali.',
    description_en: 'Interactive workshop on gender mainstreaming strategies in humanitarian and development programs in Mali.',
    room: 'Salle Bleue A',
    capacity: 100,
    registered: 89,
    speakers: ['3', '5', '7', '10'],
    category: 'Atelier',
    category_en: 'Workshop',
    color: '#10B981',
  },
  {
    id: 'panel-3',
    day: 2,
    date: '2026-05-15',
    startTime: '10:00',
    endTime: '12:30',
    title: 'Innovations technologiques au service de l\'humanitaire',
    title_en: 'Technological innovations for humanitarian action',
    description: 'Explorer comment les nouvelles technologies transforment la réponse humanitaire : IA, drones, applications mobiles, blockchain pour la transparence.',
    description_en: 'Explore how new technologies transform humanitarian response: AI, drones, mobile apps, blockchain for transparency.',
    room: 'Salle Innovation',
    capacity: 150,
    registered: 150,
    speakers: ['1', '4', '5', '8', '9'],
    category: 'Conférence',
    category_en: 'Conference',
    color: '#D4AF37',
  },
]

export const mockNGOs = [
  {
    id: '1',
    name: 'Action Contre la Faim Mali',
    acronym: 'ACF',
    logo: '🌾',
    domain: 'Nutrition & Sécurité Alimentaire',
    domain_en: 'Nutrition & Food Security',
    description: 'Organisation humanitaire luttant contre la faim et la malnutrition au Mali depuis 1995.',
    description_en: 'Humanitarian organization fighting hunger and malnutrition in Mali since 1995.',
    website: 'https://actioncontrelafaim.org',
    contact: 'mali@actioncontrelafaim.org',
    employees: 250,
    beneficiaires: '180,000',
    regions: ['Mopti', 'Ségou', 'Gao'],
  },
  {
    id: '2',
    name: 'Oxfam International Mali',
    acronym: 'OXFAM',
    logo: '🤝',
    domain: 'Justice Économique & Genre',
    domain_en: 'Economic Justice & Gender',
    description: 'Confédération internationale travaillant à l\'élimination de la pauvreté et des inégalités.',
    description_en: 'International confederation working to eliminate poverty and inequality.',
    website: 'https://oxfam.org',
    contact: 'mali@oxfam.org',
    employees: 120,
    beneficiaires: '95,000',
    regions: ['Bamako', 'Sikasso', 'Koulikoro'],
  },
  {
    id: '3',
    name: 'Save the Children Mali',
    acronym: 'STC',
    logo: '👶',
    domain: 'Protection de l\'Enfance',
    domain_en: 'Child Protection',
    description: 'Défenseur des droits des enfants, œuvrant pour leur survie, développement et protection.',
    description_en: 'Advocate for children\'s rights, working for their survival, development and protection.',
    website: 'https://savethechildren.net',
    contact: 'mali@savethechildren.org',
    employees: 180,
    beneficiaires: '220,000',
    regions: ['Mopti', 'Tombouctou', 'Bamako'],
  },
  {
    id: '4',
    name: 'International Rescue Committee',
    acronym: 'IRC',
    logo: '🏥',
    domain: 'Santé & Eau-Hygiène',
    domain_en: 'Health & WASH',
    description: 'Organisation humanitaire répondant aux crises et aux déplacements forcés de populations.',
    description_en: 'Humanitarian organization responding to crises and forced population displacement.',
    website: 'https://rescue.org',
    contact: 'mali@rescue.org',
    employees: 200,
    beneficiaires: '150,000',
    regions: ['Ménaka', 'Gao', 'Mopti'],
  },
  {
    id: '5',
    name: 'Handicap International Mali',
    acronym: 'HI',
    logo: '♿',
    domain: 'Inclusion & Handicap',
    domain_en: 'Inclusion & Disability',
    description: 'Organisation internationale défendant les droits des personnes handicapées en situations de crise.',
    description_en: 'International organization defending the rights of people with disabilities in crisis situations.',
    website: 'https://hi.org',
    contact: 'mali@hi.org',
    employees: 80,
    beneficiaires: '45,000',
    regions: ['Bamako', 'Kayes', 'Ségou'],
  },
]

export const mockSponsors = {
  platine: [
    { id: '1', name: 'Banque Mondiale', logo: '🏦', logoUrl: '/logos/world-bank.svg', url: 'https://worldbank.org', description: 'Partenaire financier principal' },
    { id: '2', name: 'USAID', logo: '🇺🇸', logoUrl: '/logos/usaid.svg', url: 'https://usaid.gov', description: 'Agence américaine de développement' },
  ],
  or: [
    { id: '3', name: 'Union Européenne', logo: '🇪🇺', logoUrl: '/logos/eu.svg', url: 'https://europa.eu', description: 'Fonds EU pour le développement' },
    { id: '4', name: 'PNUD Mali', logo: '🌐', logoUrl: '/logos/undp.svg', url: 'https://undp.org', description: 'Programme des Nations Unies' },
    { id: '5', name: 'AFD Mali', logo: '🏛️', logoUrl: '/logos/afd.svg', url: 'https://afd.fr', description: 'Agence Française de Développement' },
  ],
  argent: [
    { id: '6', name: 'Orange Mali', logo: '🍊', logoUrl: '/logos/orange.svg', url: 'https://orange.ml', description: 'Partenaire Télécoms' },
    { id: '7', name: 'BMS-Sa', logo: '💳', logoUrl: '', url: '#', description: 'Banque Malienne de Solidarité' },
    { id: '8', name: 'Ecobank Mali', logo: '🏪', logoUrl: '/logos/ecobank.svg', url: 'https://ecobank.com', description: 'Partenaire Financier' },
    { id: '9', name: 'MTN Mali', logo: '📱', logoUrl: '/logos/mtn.svg', url: '#', description: 'Partenaire Mobile Money' },
  ],
  media: [
    { id: '10', name: 'ORTM', logo: '📺', logoUrl: '', url: '#', description: 'Télévision nationale' },
    { id: '11', name: 'Radio Kledu', logo: '📻', logoUrl: '', url: '#', description: 'Radio partenaire' },
    { id: '12', name: 'Mali Actu', logo: '📰', logoUrl: '', url: '#', description: 'Presse en ligne' },
  ],
}

export const contactSponsoring = {
  name: 'Aminata HAIDARA',
  title: 'Responsable Partenariats & Sponsoring – SAHD 2026',
  phone: '+223 94 74 94 94',
  whatsapp: '+223 94 74 94 94',
  email: 'sponsoring@sahd-mali.org',
  email2: 'contact@sahd-mali.org',
  address: 'Bamako, Mali',
}

export const eventInfo = {
  name: 'Salon de l\'Action Humanitaire et du Développement',
  name_en: 'Humanitarian Action and Development Fair',
  acronym: 'SAHD',
  edition: '1ère Édition',
  edition_en: '1st Edition',
  dates: '14–16 Mai 2026',
  dates_en: 'May 14–16, 2026',
  location: 'Palais des Congrès de Bamako, Mali',
  tagline: 'Ensemble pour un Mali solidaire et durable',
  tagline_en: 'Together for a Solidarity and Sustainable Mali',
  description: 'Le SAHD est la plateforme nationale de référence pour promouvoir l\'action humanitaire, réunir les acteurs du développement et catalyser des partenariats stratégiques pour un Mali résilient.',
  description_en: 'SAHD is the national reference platform to promote humanitarian action, bring together development actors and catalyze strategic partnerships for a resilient Mali.',
  stats: {
    speakers: '50+',
    participants: '2000+',
    ngos: '100+',
    panels: '20+',
    countries: '15+',
  },
}
